# Generated by Django 2.1.7 on 2019-03-15 16:53

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190313_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='book',
            name='slugger',
            field=slugger.fields.AutoSlugField(blank=True, null=True, populate_from='title', unique=True),
        ),
    ]
